version: '3.8'

services:
  rapidcare-api:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=development-secret-key
    volumes:
      - ./back-end:/app
      - /app/node_modules
    depends_on:
      - rapidcare-db

  rapidcare-web:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    volumes:
      - ./front-end:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - rapidcare-api

  rapidcare-db:
    image: alpine:latest
    volumes:
      - rapidcare_data:/data
    command: tail -f /dev/null

volumes:
  rapidcare_data: